{% set name = "wibl-python" %}
{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CCOMJHC/WIBL/archive/refs/heads/release-wibl-python-1.2.0.tar.gz
  # TODO: Revert to this after GitHub release has been created
  # url: https://github.com/CCOMJHC/WIBL/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  # TODO: Update hash after GitHub release has been created
  sha256: e248fdc1727526620d6b015dbb0a401bfef3f9e90059e4dbcfb68463d8fde305

build:
  entry_points:
    - wibl = wibl.command:cli
  noarch: python
  script: |
    {{ PYTHON }} -m pip install ./wibl-python/wibl-manager
    {{ PYTHON }} -m pip install ./wibl-python -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - csbschema ==1.1.2
    - gdal
    - matplotlib-base
    - boto3 ~=1.20
    - requests ~=2.32.4
    - numpy >=1.23.5
    - pynmea2 ~=1.18
    - pygmt ~=0.10.0
    - rasterio ~=1.3.0
    - click~=8.2.1
    - dataclasses-json ~=0.5.7
    - deepmerge
    - geopandas
    - geoalchemy2
test:
  imports:
    - wibl
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - wibl --help

about:
  home: https://github.com/CCOMJHC/WIBL/tree/wibl-python-1.1.0/wibl-python
  summary: 'Python tools for WIBL low-cost data logger system.'
  description: |
    Python tools for WIBL low-cost data logger system. For more information on WIBL.
  license: MIT
  license_family: MIT
  license_file: wibl-python/LICENSE.txt
  doc_url: https://wibl.ccom.unh.edu/
  dev_url: https://github.com/CCOMJHC/WIBL

extra:
  recipe-maintainers:
    - selimnairb
    - brian-r-calder
